// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tetragonreceiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tetragonreceiver")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                           metric.Meter
	mu                              sync.Mutex
	registrations                   []metric.Registration
	TetragonreceiverConsumeErrors   metric.Int64Counter
	TetragonreceiverEventsDropped   metric.Int64Counter
	TetragonreceiverEventsReceived  metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.TetragonreceiverConsumeErrors, err = builder.meter.Int64Counter(
		"otelcol_tetragonreceiver_consume_errors",
		metric.WithDescription("Number of failures handing converted logs to the next consumer [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.TetragonreceiverEventsDropped, err = builder.meter.Int64Counter(
		"otelcol_tetragonreceiver_events_dropped",
		metric.WithDescription("Number of events dropped due to worker channel queue overflow [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.TetragonreceiverEventsReceived, err = builder.meter.Int64Counter(
		"otelcol_tetragonreceiver_events_received",
		metric.WithDescription("Number of raw eBPF events read from the Tetragon gRPC stream [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
