// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/tetragon component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("tetragon")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tetragonreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
